<?php

return array(
    'telefono' => 'Phone:',
    'mariana.cargo' => 'Presidenta',
    'mariana.desc' => 'I am proud to come from a humble and ordinary family and to have been born and raised in a rural community. The circumstances of my upbringing influenced me a lot and pushed me to address the necessities of Mexico’s poor population – which I have experienced myself – through the Fundación. The main motivation for my work is the wish that children, young people, adults and the elderly can enjoy a better quality of life. I studied Business Administration. I specialized in NGO development, management and public relations and promote the work of the Fundación. I set my aims high and strive for the complete fulfillment of the social objectives of the organization. My life’s experiences motivated me to work altruistically, giving me strength to reach out even for the most remote areas, in order to address people’s needs through social assistance and community development in Mexico.',
    'amaranta.cargo' => 'Subdirectora de desarrollo interinstitucional y comunicación',
    'amaranta.desc' => 'I have participated as volunteer in the activities of a number of NGO´s. I helped collecting and distributing donations. Before finishing my Master in Applied Public Management I got the chance to work as voluntary teacher in the “Network for Voluntary Service” in Kenia. These experiences gave me the opportunity to get in contact with young talents who are often limited by their living conditions. Therefore, I dedicate myself to the promotion of young people’s potential. ',
    'feliciano.cargo' => 'Director general',
    'feliciano.desc' => 'In the Fundación we assumed the difficult task to help the most vulnerable population. We know that it needs a team to promote the development of a society with better and more dignified living conditions for its population.',
    'eduardo.cargo' => 'Director de Administración',
    'eduardo.desc' => 'I have lived among people in extreme poverty for many years. Therefore, I got the opportunity to participate in numerous activities of organizations in benefit of the population with the greatest needs. I am a Graduate of the Arts, thus I participate mainly in the artistic events of the Fundación. Because I know how hunger and cold feel like, I have already worked in marginalized locations in Puebla, Veracruz, Jalisco, Querétaro and Guanajuato.',
    'hugo.cargo' => 'Director de desarrollo interinstitucional y comunicación',
    'hugo.desc' => 'Despite of difficulties in some moments, the circumstances in which I have lived so far have been favorable. My studies of philosophy gave me the possibility to become a teacher in different academic fields. Furthermore, I have written articles for various printed media of communication. My specialization as investigator helps me to administer government programs, programs of institutional development and the exchange of non-governmental organisms with the social society. I am convinced that the Fundación can help to develop Mexico’s communities and, thus, modify social structures in benefit of all people.',
    'rebecca.cargo' => 'Voluntaria',
    'rebecca.desc' => 'I was born and raised in Germany, where I graduated in Geography. I have specialized in human geography, in particular food security in countries of the global south. I worked as a trainee in the Center of International Development and Environmental Research and participated in various projects concerning global problems and sustainable development. After my studies I went to Mexico to learn more about its history and culture which I am quite interested in. Working in the Fundación helps me to get in touch with the people from the field and therefore, to get a better idea of their culture and traditions.',
    'efren.cargo' => 'Coordinador de Sistemas',
    'efren.desc' => 'I collaborate with the Fundación Vive Mejor A.C.S  since the beginning of its activities. Due to my profession – engineer of computer systems – I support the Fundación as volunteer in questions of computer systems and technical problems, in administration and in web design. I dedicate my work to the Fundación because of its commitment with the most marginalized communities.',
);