<?php

return array(
    'telefono' => 'Telefon:',
    'mariana.cargo' => 'Präsidentin',
    'mariana.desc' => 'Ich bin stolz darauf, aus einer bescheidenen und einfachen Familie zu kommen und in einer ruralen Gemeinde geboren und aufgewachsen zu sein. Diese Umstände haben mich geprägt und mich dazu angestoβen mit Hilfe der Fundación die Missstände zu bekämpfen. Meine Motivation diese Arbeit fortzuführen, ist der Wunsch eine bessere Lebensqualität für Kinder, Jugendliche, Erwachsene und Senioren zu schaffen. Durch mein Studium der Betriebswirtschaftslehre habe ich Erfahrungen gesammelt und mich anschlieβend auf die Entwicklung von NGOs, Management, Kontaktknüpfung und die Promotion der in der Fundación betriebenen Arbeit spezialisiert. Dies hat mich motiviert höhere Ziele anzusetzen und mich in der Arbeit zur Verwirklichung  des sozialen Kernziels der Fundación gestärkt. Alle diese Erfahrungen, die ich während meines Studiums und der Arbeit sammeln durfte, haben mich zu Nächstenliebe motiviert. Sie haben mir Kraft und Ausdauer gegeben, den Menschen, die in gröβter Vulnerabilität leben, durch soziale Fürsorge und Community Development in meiner Heimat Mexiko zu unterstützen.',
    'amaranta.cargo' => 'Stellvertretende Geschäftsführerin der interinstitutionellen Entwicklung und Kommunikation',
    'amaranta.desc' => 'Einen Groβteil meines Lebens habe ich damit verbracht in Sammelaktionen und Verteilungen von Hilfsmitteln in verschiedenen NGOs zu arbeiten. Bevor ich mein Studium des öffentlich angewandten Management beendet habe, hatte ich das Glück als freiwillige Lehrkraft in der NGO “Network for Voluntary Service” in Kenia zu arbeiten. Diese Lebenserfahrung hat mir die Möglichkeit gegeben, talentierte Jugendliche kennenzulernen, die jedoch durch ihre Lebensbedingungen determiniert sind. Somit habe ich mir vorgenommen diesen Jugendlichen zu unterstützen und ihr Potenzial zu fördern.',
    'feliciano.cargo' => 'Generaldirektor',
    'felicianp.desc' => 'In der Fundación haben wir es uns zur Aufgabe gemacht, Mitverantwortung für die Bevölkerung zu übernehmen. Dies soll zu der Entwicklung der Gesellschaft beitragen und würdigere Lebensverhältnisse der Menschen schaffen. Wir wissen, dass dies nur mit Hilfe eines Teams bewältigt werden kann.',
    'eduardo.cargo' => 'Direktor der Verwaltung',
    'eduardo.desc' => 'Ich habe lange Zeit mit Menschen in groβer Armut lebend und denen es an materiellen Eigentum mangelt, zusammengelebt. Auf diese Weise hatte ich das Glück, in verschiedenen Aktivitäten von Organisationen zugunsten der Menschen in gröβter Not mitzuarbeiten. Ich bin Absolvent eines Lehramtstudiums und mit meinen Fähigkeiten und meinem Wissen, trage ich hauptsächlich zu den künstlerischen und musikalischen Events der Fundación bei. Die eigenen Erfahrungen von Kälte und Hunger in meinem Leben haben mich motiviert in vielen verschiedenen abgelegenen Lokalitäten in Puebla, Veracruz, Jalisco, Querétaro und Guanajuato mitzuarbeiten.',
    'hugo.cargo' => 'Geschäftsführer der interinstitutionellen Entwicklung und Kommunikation ',
    'hugo.desc' => 'Trotz einigen schwierigen Momenten in meinem Leben, wuchs ich dennoch unter günstigen Bedingungen auf. Mein Studium der Philosophie hat mir die Chance gegeben darauf aufbauend als Dozent zu arbeiten. Auβerdem habe ich Artikel für verschiedene Zeitungen verfasst. Meine Fähigkeiten in der Forschung haben mir geholfen die Rolle als Leiter von Regierungsprogrammen sowie von Programmen der institutionellen Entwicklung und im Austausch von Nicht-Regierungs-Organismen mit der Zivilgesellschaft zu übernehmen. Ich bin davon überzeugt, dass die Fundación ein Mittel ist um die Entwicklung der Gemeinden voranzutreiben und somit die sozialen Strukturen zugunsten aller zu verändern.',
    'rebecca.cargo' => 'Voluntärin',
    'rebecca.desc' => 'Ich bin in Deutschland geboren und aufgewachsen. In meinem Studium der Geographie habe ich mich auf humangeographische Themen in Länder des globalen Südens spezialisiert. Im Zentrum für international Entwicklungs- und Umweltforschung war ich Praktikantin und habe in verschiedenen Projekten im Bereich Politik, Umwelt und Humangeographie mitgearbeitet. Ich bin nach Mexico gekommen um selbst einmal das Leben in einem Land auβerhalb Europas sowie deren Kultur kennenzulernen. In der Fundación kann ich mein Wissen und meine Fähigkeiten, die ich mir während des Studiums angeeignet habe, anwenden und weiterentwickeln. Zudem erlaubt mir die Arbeit in der Fundación, diese in ihrer sozialen Arbeit zu unterstützen und dabei das Land und die Leute Mexicos kennenzulernen.',
    'efren.cargo' => 'Koordinator des Computersystems',
    'efren.desc' => 'Seit deren Gründung arbeite ich in der Fundación Vive Mejor AC mit. Aufgrund meines Berufes als Systemsingenieur unterstütze ich die Fundación als Freiwilliger bei Computersystemen, bei technischen Angelegenheiten im Bereich der Informatik sowie bei der Verwaltung und dem Entwurf der Internetseite. Ich engagiere  mich deshalb in der Fundación, weil mich die Arbeit in den höchst abgelegenen Gemeinden anspricht.',
);