<?php

return array(
    'telefono' => 'Teléfono:',
    'mariana.cargo' => 'Presidenta',
    'mariana.desc' => 'Me siento orgullosa de provenir de una de una familia humilde y sencilla, de haber nacido y crecido en una comunidad rural, circunstancias que me han llevado a contribuir, por medio de la Fundación, a disminuir carencias por las que yo misma pasé, deseando que los niños, jóvenes, adultos y adultos mayores puedan gozar de una mejor calidad de vida, ésa es mi motivación para continuar con mi labor. He estudiado la Licenciatura en Administración de Empresas, y aunado a la experiencia de estos años, me he especializado en el desarrollo de las ONG´s, la gestión, vinculación, relación y promoción del trabajo que se realiza en la Fundación, lo que me ha llevado a incrementar las metas y así lograr el cumplimiento del objeto social de la Organización. Todas estas experiencias me han sensibilizado en la vocación filantrópica, dándome fuerzas para llegar a los lugares más rezagados para solventar las necesidades de la gente por medio de la asistencia social y desarrollo comunitario en nuestro querido México. ',
    'amaranta.cargo' => 'Subdirectora de desarrollo interinstitucional y comunicación',
    'amaranta.desc' => 'Durante gran parte de mi vida, he colaborado como voluntaria en diversas ONGs en actividades como colectas y repartición de apoyos. Tiempo antes de terminar mis estudios de Maestría en Gestión Pública Aplicada, tuve la dicha de trabajar como profesora voluntaria en la ONG Network for Voluntary Service en Kenia. Éstas experiencias de vida me han dado la oportunidad de reconocer que hay jóvenes talentosos, pero que están limitados por sus condiciones de vida, por ello me he propuesto donde la juventud pueda verdaderamente desarrollar sus potenciales. ',
    'feliciano.cargo' => 'Director general',
    'felicianp.desc' => 'Para coadyuvar en la difícil tarea que tenemos todos de corresponsabilizarnos con la población más vulnerable, sabedor de que solo en equipo se promueve el desarrollo de una mejor sociedad y con seres humanos en condiciones de vida mas dignas. ',
    'eduardo.cargo' => 'Director de Administración',
    'eduardo.desc' => 'Durante mucho tiempo he convivido con gente de escasos recursos, que viven en pobreza extrema. Por ello he tenido la dicha de participar en múltiples actividades de Organizaciones en beneficio de la gente más necesitada. Soy Licenciado en Docencia del Arte, y con el talento que tengo, participo principalmente en los eventos artísticos de la Fundación. Dado que he sentido en mi vida el frio y el hambre he colaborado en localidades marginadas en Puebla, Veracruz, Jalisco, Querétaro y Guanajuato. ',
    'hugo.cargo' => 'Director de desarrollo interinstitucional y comunicación',
    'hugo.desc' => 'Las circunstancias en las que he vivido han sido favorables a pesar de que en ciertos momentos he padecido de dificultades. Mis estudios en Filosofía me han dado la oportunidad de ser docente en diferentes grados académicos; además he sido articulista en medios de comunicación impresos. Mi especialización como investigador me ha ayudado a ser gestor de Programas de Gobierno, desarrollo institucional y vinculador de Organismos no gubernamentales con la sociedad civil. Tengo la idea clara de que la Fundación es un medio para lograr el desarrollo de las comunidades y así poder modificar las estructuras sociales en beneficio de todos. ',
    'rebecca.cargo' => 'Voluntaria',
    'rebecca.desc' => 'Nací y crecí en Alemania, lugar donde también cursé mis estudios superiores en Bachelor en Geografía, especializándome en relaciones internacionales. Fui practicante en el Center of international Development and Environmental Research, donde trabajé en diferentes proyectos acerca de problemas globales y desarrollo sustentable. He venido a México porque he conocido su cultura e historia y me ha interesado mucho. Ahora que vivo aquí, quiero desarrollar mis habilidades que he aprendido en la escuela, además de conocer más a profundidad a la gente de este país así como sus tradiciones. ',
    'efren.cargo' => 'Coordinador de Sistemas',
    'efren.desc' => 'He colaborado con la Fundación Vive Mejor AC desde que iniciaron sus actividades. Desde mi profesión, Ingeniero en Sistemas Computacionales, apoyo como voluntario en sistemas y asuntos técnicos de informática, administración y diseño del Sitio Web. Me he comprometido más con las Organización por el trabajo que realiza en las comunidades más marginadas. ',
);